---
id: faction
title: Commandes pour les factions 
category: commands
description: Vous souhaitez devenir les plus riches du serveur ? Travaillez en equipe pour évoluer plus vite sur le serveur ? Creez ou rejoignez un Faction ! 
icon: "textures/blocks/command_block.png"
---
___
## Description

Une faction est sorte de team où plusieurs joueurs se retrouvent pour réaliser des actions en groupe, du pvp, des bases, des construictions etc...
C'est un lieu basé sur la confiance de ces membres malgré le faite que la trahison est autorisé sur le serveur. De nombreux avantage dans le gamplay vous seront apportés si vous etes dans une faction ! 

Permissions en fonction du rand dans la faction 
## Commande disponible & explication 

* ``/f help ``: Permet de visualiser une liste complete des commandes lié au faction disponible sur le serveur ig directement
* ``/f info <faction> ``: Permet de visualiser tout les informations importante sur une faction comme ca date de creation, ces membres etc... 
* ``/f create <nom> ``: Permet la cration d'une faction avec un nom choisie. 
** Informations **: Vous ne pouvez pas creer deux faction du même nom ni creer de faction si vous en avez déjà une. 
* ``/f delete ``: Permet de supprimer ca faction. 
** Informations **: Seul le chef de la faction peut delete ca faction, ceci supprimera toutes les données de cette faction. 
* ``/f invite <pseudo> ``: Permet d'inviter un joueur dans ca faction. 
** Information ** : Il faut bien rentrer le pseudo exacte de joueur qui doit etre ajouté ( mettre " au debut et à la fin du pseudo si il y a des espace ). 
* ``/f accept ``: Permet d'accepter une invitation pour rejoindre une faction. 
* ``/f deny ``: Permet de refusé une invitation pour rejoindre une faction. 
* ``/f promote <pseudo> ``: Permet d'augementer de rand un membre d'une faction. 
** Information ** : Seul le chef d'une faction peut utiliser cette commande sur un de ces membres.
* ``/f demote <pseudo> ``: Permet de retrograder d'officier à memebre une personne de votre faction. 
** Information ** : Seul le chef d'une faction peut utiliser cette commande sur un de ces officiers.
* ``/f kick <pseudo> ``: Permet d'expulser une personne de votre faction. 
* ``/f leave ``: Permet de quitter votre faction.  
* ``/f description <description> ``: Permet de modifier la description de votre faction.
** Informations ** : Seul le chef d'une faction peut changer ceci, une limite de 200 carractères est defini sur les descriptions de faction.  
